CREATE TABLE [dbo].[Nominations] (
    [NominationId]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [UserId]                BIGINT        NOT NULL,
    [SchemeId]              BIGINT        NOT NULL,
    [IntakeId]              BIGINT        NOT NULL,
    [NominationStatusId]    BIGINT        NOT NULL,
    [MobileNo]              VARCHAR (50)  NULL,
    [Gender]                VARCHAR (10)  NULL,
    [MsilTenure]            DECIMAL(5,2)  NULL,
    [Grade]                 VARCHAR (50)  NULL,
    [RelevantPrevExp]       DECIMAL(5,2)  NULL,
    [VerticalId]            BIGINT        NULL,
    [DivisionId]            BIGINT        NULL,
    [DesignationId]         BIGINT        NULL,
    [DepartmentId]          BIGINT        NULL,
    [LocationId]            BIGINT        NULL,
    [InstitueId]            BIGINT        NULL,
    [ApprovalBy1]           BIGINT        NULL,
    [ApprovalDate1]         DATETIME      NULL,
    [ApprovalRemarks1]      VARCHAR (100) NULL,
    [ApprovalBy2]           BIGINT        NULL,
    [ApprovalDate2]         DATETIME      NULL,
    [ApprovalRemarks2]      VARCHAR (100) NULL,
    [AdmissionStatusId]     BIGINT        NULL,
    [AdmissionAcceptedDate] DATETIME      NULL,
    [IsExamTaken]           BIT           NULL,
    [Rank]                  DECIMAL(5,2)  NULL,
    [Score]                 DECIMAL(5,2)  NULL,
    [IsScoreApprove]        BIT           CONSTRAINT [DF_Nominations_IsScoreApprove] DEFAULT ((0)) NOT NULL,
    [IsPublish]             BIT           CONSTRAINT [DF_Nominations_IsPublish] DEFAULT ((0)) NOT NULL,
    [IsActive]              BIT           CONSTRAINT [DF_Nominations_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]           DATETIME      CONSTRAINT [DF_Nominations_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]             BIGINT        CONSTRAINT [DF_Nominations_CreatedBy] DEFAULT ((1)) NOT NULL,
    [UpdatedDate]           DATETIME      CONSTRAINT [DF_Nominations_ModifiedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]             BIGINT        CONSTRAINT [DF_Nominations_ModifiedBy] DEFAULT ((1)) NOT NULL,
    [IsDeleted]             BIT           CONSTRAINT [DF_Nominations_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Nominations] PRIMARY KEY CLUSTERED ([NominationId] ASC)
);

