CREATE TABLE [dbo].[Users] (
    [UserId]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [Email]       VARCHAR (100) NULL,
    [FirstName]   VARCHAR (50)  NOT NULL,
    [LastName]    VARCHAR (50)  NULL,
    [MobileNo]    VARCHAR (50)  NULL,
    [ManagerId]   BIGINT        NULL,
    [MsilUserId]  BIGINT        NOT NULL,
    [MsilUserName] VARCHAR (50) NULL,
    [Doj]         DATETIME      NULL,
    [Dos]         DATETIME      NULL,
    [Dol]         DATETIME      NULL,
    [Password]    VARCHAR (255) NULL,
    [Salt]        VARCHAR (255) NULL,
    [VerticalId]  BIGINT        NULL,
    [DivisionId]  BIGINT        NULL,
    [DesignationId] BIGINT      NULL,
    [DepartmentId] BIGINT       NULL,
    [LocationId]  BIGINT        NULL,
    [IsAdmin]     BIT           CONSTRAINT [DF_Users_IsAdmin] DEFAULT ((0)) NOT NULL,
    [IsActive]    BIT           CONSTRAINT [DF_Users_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate] DATETIME      CONSTRAINT [DF_Users_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]   BIGINT        CONSTRAINT [DF_Users_CreatedBy] DEFAULT ((1)) NOT NULL,
    [UpdatedDate] DATETIME      CONSTRAINT [DF_Users_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]   BIGINT        CONSTRAINT [DF_Users_UpdatedBy] DEFAULT ((1)) NOT NULL,
    [IsDeleted]   BIT           CONSTRAINT [DF_Users_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserId] ASC)
);
